CREATE TABLE IF NOT EXISTS quizzes
(
    id                BIGSERIAL PRIMARY KEY,
    language          BIGINT  NOT NULL REFERENCES languages ON DELETE RESTRICT,
    skill             INTEGER NOT NULL,
    name              TEXT    NOT NULL,
    background_color  TEXT    NOT NULL,
    intro_phrase      TEXT    NOT NULL,
    image_resource    TEXT    NOT NULL,
    progression_order INTEGER NOT NULL
);


INSERT INTO quizzes (id, language, skill, name, background_color, intro_phrase, image_resource, progression_order)
VALUES (1, 1, 1, 'Animals', '#FFFBC1', 'Enter animal name…', 'animals', 1),
       (2, 1, 1, 'Fruits', '#B6E2A1', 'Enter fruit name…', 'fruits', 2),
       (3, 1, 1, 'Vehicles', '#FEBE8C', 'Enter vehicle name…', 'vehicles', 3),
       (4, 1, 1, 'Clothing', '#90A17D', 'Enter garment name…', 'clothing', 4),
       (5, 1, 1, 'Sports', '#AAC4FF', 'Enter sport name…', 'sports', 5),
       (7, 2, 1, 'Tiere', '#FFFBC1', 'Schreib das Tier…', 'animals', 1),
       (8, 2, 1, 'Obst', '#B6E2A1', 'Schreib das Obst…', 'fruits', 2),
       (9, 2, 1, 'Fahrzeuge', '#FEBE8C', 'Schreib das Fahrzeug…', 'vehicles', 3),
       (10, 2, 1, 'Kleidung', '#90A17D', 'Schreib das Kleidungsstück…', 'clothing', 4),
       (11, 2, 1, 'Sport', '#AAC4FF', 'Schreib der Sport…', 'sports', 5),
       (12, 3, 1, 'Animales', '#FFFBC1', 'Introduce el animal…', 'animals', 1),
       (13, 3, 1, 'Frutas', '#B6E2A1', 'Introduce la fruta…', 'fruits', 2),
       (14, 3, 1, 'Vehículos', '#FEBE8C', 'Introduce el vehículo…', 'vehicles', 3),
       (15, 3, 1, 'Ropa', '#90A17D', 'Introduce la prenda…', 'clothing', 4),
       (16, 3, 1, 'Deportes', '#AAC4FF', 'Introduce el deporte…', 'sports', 5),
       (17, 1, 2, 'Animals', '#FFFBC1', 'Enter animal name…', 'animals', 1),
       (18, 1, 2, 'Fruits', '#B6E2A1', 'Enter fruit name…', 'fruits', 2),
       (19, 1, 2, 'Vehicles', '#FEBE8C', 'Enter vehicle name…', 'vehicles', 3),
       (20, 1, 2, 'Clothing', '#90A17D', 'Enter garment name…', 'clothing', 4),
       (21, 1, 2, 'Sports', '#AAC4FF', 'Enter sport name…', 'sports', 5),
       (22, 1, 3, 'Animals', '#FFFBC1', 'Choose animal picture…', 'animals', 1),
       (23, 1, 4, 'Animals', '#FFFBC1', 'Say the animal name…', 'animals', 1),
       (24, 1, 3, 'Fruits', '#B6E2A1', 'Choose fruit picture…', 'fruits', 2),
       (25, 1, 3, 'Vehicles', '#FEBE8C', 'Choose vehicle picture…', 'vehicles', 3),
       (26, 1, 3, 'Clothing', '#90A17D', 'Choose garment picture…', 'clothing', 4),
       (27, 1, 3, 'Sports', '#AAC4FF', 'Choose sport picture…', 'sports', 5),
       (28, 3, 2, 'Animales', '#FFFBC1', 'Introduce el animal…', 'animals', 1),
       (29, 3, 2, 'Frutas', '#B6E2A1', 'Introduce la fruta…', 'fruits', 2),
       (30, 3, 2, 'Vehículos', '#FEBE8C', 'Introduce el vehículo…', 'vehicles', 3),
       (31, 3, 2, 'Ropa', '#90A17D', 'Introduce la prenda…', 'clothing', 4),
       (32, 3, 2, 'Deportes', '#AAC4FF', 'Introduce el deporte…', 'sports', 5),
       (33, 3, 3, 'Animales', '#FFFBC1', 'Elige el animal…', 'animals', 1),
       (34, 3, 3, 'Frutas', '#B6E2A1', 'Elige la fruta…', 'fruits', 2),
       (35, 3, 3, 'Vehículos', '#FEBE8C', 'Elige el vehículo…', 'vehicles', 3),
       (36, 3, 3, 'Ropa', '#90A17D', 'Elige la prenda…', 'clothing', 4),
       (37, 3, 3, 'Deportes', '#AAC4FF', 'Elige el deporte…', 'sports', 5),
       (38, 2, 2, 'Tiere', '#FFFBC1', 'Schreib das Tier…', 'animals', 1),
       (39, 2, 2, 'Obst', '#B6E2A1', 'Schreib das Obst…', 'fruits', 2),
       (40, 2, 2, 'Fahrzeuge', '#FEBE8C', 'Schreib das Fahrzeug…', 'vehicles', 3),
       (41, 2, 2, 'Kleidung', '#90A17D', 'Schreib das Kleidungsstück…', 'clothing', 4),
       (42, 2, 2, 'Sport', '#AAC4FF', 'Schreib der Sport…', 'sports', 5),
       (43, 2, 3, 'Tiere', '#FFFBC1', 'Tierbild auswählen…', 'animals', 1),
       (44, 2, 3, 'Obst', '#B6E2A1', 'Obstbild auswählen…', 'fruits', 2),
       (45, 2, 3, 'Fahrzeuge', '#FEBE8C', 'Fahrzeugbild auswählen…', 'vehicles', 3),
       (46, 2, 3, 'Kleidung', '#90A17D', 'Kleidungbild auswählen…', 'clothing', 4),
       (47, 2, 3, 'Sport', '#AAC4FF', 'Sportbild auswählen…', 'sports', 5),
       (48, 1, 4, 'Fruits', '#B6E2A1', 'Say the fruit name…', 'fruits', 2),
       (49, 1, 4, 'Vehicles', '#FEBE8C', 'Say the vehicle name…', 'vehicles', 3),
       (50, 1, 4, 'Clothing', '#90A17D', 'Say the garment name…', 'clothing', 4),
       (51, 1, 4, 'Sports', '#AAC4FF', 'Say the sport name…', 'sports', 5),
       (52, 3, 4, 'Animales', '#FFFBC1', 'Di el animal…', 'animals', 1),
       (53, 3, 4, 'Frutas', '#B6E2A1', 'Di la fruta…', 'fruits', 2),
       (54, 3, 4, 'Vehículos', '#FEBE8C', 'Di el vehículo…', 'vehicles', 3),
       (55, 3, 4, 'Ropa', '#90A17D', 'Di la prenda…', 'clothing', 4),
       (56, 3, 4, 'Deportes', '#AAC4FF', 'di el deporte…', 'sports', 5),
       (57, 2, 4, 'Tiere', '#FFFBC1', 'Sagt das Tier…', 'animals', 1),
       (58, 2, 4, 'Obst', '#B6E2A1', 'Sagt das Obst…', 'fruits', 2),
       (59, 2, 4, 'Fahrzeuge', '#FEBE8C', 'Sagt das Fahrzeug…', 'vehicles', 3),
       (60, 2, 4, 'Kleidung', '#90A17D', 'Sagt das Kleidungsstück…', 'clothing', 4),
       (61, 2, 4, 'Sport', '#AAC4FF', 'Sagt der Sport…', 'sports', 5),
       (62, 4, 1, 'Animals', '#FFFBC1', 'Introdueix l''animal…', 'animals', 1),
       (63, 4, 1, 'Fruites', '#B6E2A1', 'Introdueix la fuita…', 'fruits', 2),
       (64, 4, 1, 'Vehicles', '#FEBE8C', 'Introdueix el vehicle…', 'vehicles', 3),
       (65, 4, 1, 'Roba', '#90A17D', 'Introdueix la roba…', 'clothing', 4),
       (66, 4, 1, 'Esports', '#AAC4FF', 'Introdueix el sport…', 'sports', 5),
       (67, 4, 2, 'Animals', '#FFFBC1', 'Introdueix l''animal…', 'animals', 1),
       (68, 4, 2, 'Fruites', '#B6E2A1', 'Introdueix la fuita…', 'fruits', 2),
       (69, 4, 2, 'Vehicles', '#FEBE8C', 'Introdueix el vehicle…', 'vehicles', 3),
       (70, 4, 2, 'Roba', '#90A17D', 'Introdueix la roba…', 'clothing', 4),
       (71, 4, 2, 'Esports', '#AAC4FF', 'Introdueix el sport…', 'sports', 5),
       (72, 4, 3, 'Animals', '#FFFBC1', 'Tria l''animal…', 'animals', 1),
       (73, 4, 3, 'Fruites', '#B6E2A1', 'Tria la fuita…', 'fruits', 2),
       (74, 4, 3, 'Vehicles', '#FEBE8C', 'Tria el vehicle…', 'vehicles', 3),
       (75, 4, 3, 'Roba', '#90A17D', 'Tria la roba…', 'clothing', 4),
       (76, 4, 3, 'Esports', '#AAC4FF', 'Tria el sport…', 'sports', 5),
       (77, 4, 4, 'Animals', '#FFFBC1', 'Digues l''animal…', 'animals', 1),
       (78, 4, 4, 'Fruites', '#B6E2A1', 'Digues la fuita…', 'fruits', 2),
       (79, 4, 4, 'Vehicles', '#FEBE8C', 'Digues el vehicle…', 'vehicles', 3),
       (80, 4, 4, 'Roba', '#90A17D', 'Digues la roba…', 'clothing', 4),
       (81, 4, 4, 'Esports', '#AAC4FF', 'Digues el sport…', 'sports', 5),
       (82, 5, 1, 'Animaux', '#FFFBC1', 'Entrez le nom de l''animal…', 'animals', 1),
       (83, 5, 1, 'Fruits', '#B6E2A1', 'Entrez le nom du fruit…', 'fruits', 2),
       (84, 5, 1, 'Véhicules', '#FEBE8C', 'Entrez le nom du véhicule…', 'vehicles', 3),
       (85, 5, 1, 'Vêtements', '#90A17D', 'Entrez le nom du vêtement…', 'clothing', 4),
       (86, 5, 1, 'Sports', '#AAC4FF', 'Entrez le nom du sport…', 'sports', 5),
       (87, 5, 2, 'Animaux', '#FFFBC1', 'Entrez le nom de l''animal…', 'animals', 1),
       (88, 5, 2, 'Fruits', '#B6E2A1', 'Entrez le nom du fruit…', 'fruits', 2),
       (89, 5, 2, 'Véhicules', '#FEBE8C', 'Entrez le nom du véhicule…', 'vehicles', 3),
       (90, 5, 2, 'Vêtements', '#90A17D', 'Entrez le nom du vêtement…', 'clothing', 4),
       (91, 5, 2, 'Sports', '#AAC4FF', 'Entrez le nom du sport…', 'sports', 5),
       (92, 5, 3, 'Animaux', '#FFFBC1', 'Choisissez l''image de l''animal…', 'animals', 1),
       (93, 5, 3, 'Fruits', '#B6E2A1', 'Choisissez l''image des fruits…', 'fruits', 2),
       (94, 5, 3, 'Véhicules', '#FEBE8C', 'Choisissez la photo du véhicule…', 'vehicles', 3),
       (95, 5, 3, 'Vêtements', '#90A17D', 'Choisissez la photo du vêtement…', 'clothing', 4),
       (96, 5, 3, 'Sports', '#AAC4FF', 'Choisissez la photo sportive…', 'sports', 5),
       (97, 5, 4, 'Animaux', '#FFFBC1', 'Dites le nom de l''animal…', 'animals', 1),
       (98, 5, 4, 'Fruits', '#B6E2A1', 'Dites le nom du fruit…', 'fruits', 2),
       (99, 5, 4, 'Véhicules', '#FEBE8C', 'Dites le nom du véhicule…', 'vehicles', 3),
       (100, 5, 4, 'Vêtements', '#90A17D', 'Dites le nom du vêtement…', 'clothing', 4),
       (101, 5, 4, 'Sports', '#AAC4FF', 'Dites le nom du sport…', 'sports', 5);
